<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="FunkArr.Download.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FFMpegCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FunkArr.Core\FunkArr.Core.csproj" />
  </ItemGroup>

</Project>
