services:
  funkarr:
    container_name: funkarr
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "6969:6969"
    volumes:
      - funkarr-data:/app/data
      - media:/media
    environment:
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Akka=Information
      - FunkArr__ApiKey=funkarr-dev-api-key-01
      - FunkArr__Download__DownloadPath=/media/downloads
      - FunkArr__Download__Category__tv=/media/downloads/tv
      - FunkArr__Download__Category__movies=/media/downloads/movies
    depends_on:
      - sonarr
      - radarr
      - prowlarr

  sonarr:
    container_name: sonarr
    image: ghcr.io/home-operations/sonarr:rolling
    ports:
      - "8989:8989"
    volumes:
      - sonarr-config:/config
      - media:/media
    environment:
      SONARR__AUTH__APIKEY: funkarr-dev-api-key-01
      SONARR__AUTH__METHOD: External
      SONARR__AUTH__REQUIRED: DisabledForLocalAddresses

  radarr:
    container_name: radarr
    image: ghcr.io/home-operations/radarr:rolling
    ports:
      - "7878:7878"
    volumes:
      - radarr-config:/config
      - media:/media
    environment:
      RADARR__AUTH__APIKEY: funkarr-dev-api-key-01
      RADARR__AUTH__METHOD: External
      RADARR__AUTH__REQUIRED: DisabledForLocalAddresses

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/home-operations/prowlarr:rolling
    ports:
      - "9696:9696"
    volumes:
      - prowlarr-config:/config
    environment:
      PROWLARR__AUTH__APIKEY: funkarr-dev-api-key-01
      PROWLARR__AUTH__METHOD: External
      PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses

volumes:
  funkarr-data:
  media:
  sonarr-config:
  radarr-config:
  prowlarr-config:
