<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Akka.Hosting.TestKit" />
        <PackageReference Include="Akka.Persistence.TestKit" />
        <PackageReference Include="Akka.Persistence.TestKit.Xunit" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="Verify.XunitV3" />
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FunkArr\FunkArr.csproj" />
        <ProjectReference Include="..\FunkArr.Tests.Shared\FunkArr.Tests.Shared.csproj" />
    </ItemGroup>

</Project>
