<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FunkArr.ArrApi.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FunkArr.Core\FunkArr.Core.csproj" />
  </ItemGroup>

</Project>
