<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="FunkArr.MetadataResolver.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FunkArr.Core\FunkArr.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

</Project>
