<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="FunkArr.Download.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FunkArr.Messages\FunkArr.Messages.csproj" />
    <ProjectReference Include="..\FunkArr.Persistence\FunkArr.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Akka.Hosting" />
    <PackageReference Include="Akka.Cluster.Hosting" />
    <PackageReference Include="Akka.Cluster.Sharding" />
    <PackageReference Include="Akka.Logger.Serilog" />
    <PackageReference Include="Akka.Persistence.Sql.Hosting" />
    <PackageReference Include="Akka.Streams" />
    <PackageReference Include="Servus" />
    <PackageReference Include="Servus.Akka" />
    <PackageReference Include="System.IO.Abstractions" />
  </ItemGroup>

</Project>
