<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="FunkArr.RuleSet.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FunkArr.Core\FunkArr.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\data\community\ruleset.schema.json" Link="ruleset.schema.json" />
  </ItemGroup>

</Project>
