name: CI

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ui:
    uses: st0o0/github-workflows/.github/workflows/frontend-ci.yml@main
    with:
      project-path: src/FunkArr.UI
      lint: false
      typecheck: false

  dotnet:
    uses: st0o0/github-workflows/.github/workflows/dotnet-ci.yml@main
    with:
      solution-file: FunkArr.slnx

  commits:
    uses: st0o0/github-workflows/.github/workflows/commitlint.yml@main
